media: media
filename:
  template: "{year}-{month}-{day}-{primary}.md"
  field: create
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text