media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    filename:
      template: "{year}-{month}-{day}-{primary}.md"
      field: false
    view:
      fields: [ image, title ]
    fields:
      - { name: image, label: Cover Image, type: image, options: {extensions: [png, jpg, jpeg, webp, gif]}}
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: pin, label: Pin, type: boolean }
      - { name: date, 
          label: Date,
          type: date,
          options: {
            format: yyyy-MM-dd }}
      - { name: categories, label: Categories, type: select, options: { values: [ "Gameplay", "Networking", "AI" ] } }
      - { name: tags, label: Tags, type: string }
      - { name: body, label: Body, type: rich-text }